name: Deploy

on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup `frontend` project
              run: |-
                  cd app
                  git clone https://github.com/2020-netcentric-find-my-mines/frontend frontend
                  cd frontend
                  git checkout dev
                  rm -rf .git
                  yarn
                  yarn build
                  cd ../
                  mv frontend/build static
                  cd ../
            - name: Setup Heroku
              run: |-
                  rm -rf .git
                  git init
                  git checkout master
                  git remote add staging https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
            - name: Push to Heroku
              run: |-
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"
                  git add .
                  git commit -m 'Deploy to Heroku'
                  git push staging master --force
