name: Deploy

on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup `frontend` project
              run: |-
                  cd app
                  git clone https://github.com/2020-netcentric-find-my-mines/frontend frontend
                  cd frontend
                  git checkout dev
                  rm -rf .git
                  yarn
                  yarn build
                  cd ../
                  mv frontend/build static
            - uses: akhileshns/heroku-deploy@v3.4.6
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
