export interface Player {
    id: string; // Identifier generated by Socket.IO
    name: string; // Player's name
    // account: Account | null; // Player's account
    score: number; // Player's score
}
